language: python
dist: bionic
sudo: false

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
  - DJANGO="Django>=2.2,<2.3"
  - DJANGO="Django>=3.0,<3.1"

install:
  - pip install -U coverage codecov
  - pip install -U flake8==3.6.0
  - pip install -U $DJANGO
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install black; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then pip install black; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install black; fi
  - pip freeze

script:
  - flake8 simple_history
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then black --check simple_history setup.py runtests.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then black --check simple_history setup.py runtests.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then black --check simple_history setup.py runtests.py; fi
  - coverage run setup.py test

matrix:
  exclude:
    - python: 3.4
      env: DJANGO="Django>=2.1,<2.2"
    - python: 3.4
      env: DJANGO="Django>=2.2,<2.3"

after_success: codecov
